### ISSUE TITLE
Crash with ofxBox2D

### ISSUE THREAD

**Issue by liukinwai** [ofZach/ofxTriangleMesh#2]
Hi:

ofxTriangleMesh is a great addon that exposes the switches of Triangle, which is much more power that that provided by ofxBox2D. However, it crash with ofxBox2D, probably due to duplication of use of structure triangulateio. Is there way to fix this issue?

Thanks!
Eric

**Comment by ofZach** [comment]
Can you post a small example project?  I'll take a look

**Comment by sky7x24** [comment]
Sorry for the late reply, I fix this issue already.
